services:
  tu_app:
    build: .
    runtime: nvidia
    volumes:
      - .:/app
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
